### ISSUE TITLE
Windows build fails

### ISSUE THREAD

**Issue by gonzalon** [SamVerschueren/ng2-hello-world-lazy-routing#1]
Hey Sam, thanks for your repo, great work! But I'm having problems at the build.

Here is the log. Any hints?

$ npm run build

> ng2-hello-world-aot-rollup@0.0.0 build C:\Workspace\ng2-hello-world-lazy-routing-master
> npm run clean && npm run build.compile && npm run build.shims && node make

> ng2-hello-world-aot-rollup@0.0.0 clean C:\Workspace\ng2-hello-world-lazy-routing-master
> rm -rf dist && rm -rf aot && cd build && find . ! -name 'index.html' -type f -exec rm -f {} + && cd ..

> ng2-hello-world-aot-rollup@0.0.0 build.compile C:\Workspace\ng2-hello-world-lazy-routing-master
> tsc -p tsconfig.json

> ng2-hello-world-aot-rollup@0.0.0 build.shims C:\Workspace\ng2-hello-world-lazy-routing-master
> uglifyjs node_modules/core-js/client/shim.js node_modules/zone.js/dist/zone.js node_modules/reflect-metadata/Reflect.js node_modules/systemjs/dist/system.src.js -m -o build/shims.js

bundling app\+contact\contact.module.js - (dist/app/**/*.js - dir\+contact/**/*.js) - app/main.js - app/app.module.js - app/app.routing.js - app/home/home.component.js - @angular/core - rxjs/Observable.js - rxjs/symbol/observable.js - rxjs/util/root.js - rxjs/util/toSubscriber.js - rxjs/symbol/rxSubscriber.js - rxjs/Subscriber.js - rxjs/Observer.js - rxjs/Subscription.js - rxjs/util/UnsubscriptionError.js - rxjs/util/errorObject.js - rxjs/util/tryCatch.js - rxjs/util/isFunction.js - rxjs/util/isObject.js - rxjs/util/isArray.js - rxjs/Subject.js - rxjs/SubjectSubscription.js - rxjs/util/ObjectUnsubscribedError.js - @angular/router - rxjs/operator/filter.js - @angular/platform-browser - @angular/common - rxjs/operator/mergeAll.js - rxjs/util/subscribeToResult.js - rxjs/InnerSubscriber.js - rxjs/symbol/iterator.js - rxjs/util/isPromise.js - rxjs/OuterSubscriber.js - rxjs/operator/last.js - rxjs/util/EmptyError.js - rxjs/observable/fromPromise.js - rxjs/observable/PromiseObservable.js - rxjs/operator/concatAll.js - rxjs/operator/catch.js - rxjs/operator/reduce.js - rxjs/operator/mergeMap.js - rxjs/operator/map.js - rxjs/operator/first.js - rxjs/operator/every.js - rxjs/operator/concatMap.js - rxjs/observable/of.js - rxjs/observable/ArrayObservable.js - rxjs/util/isScheduler.js - rxjs/observable/EmptyObservable.js - rxjs/observable/ScalarObservable.js - rxjs/observable/from.js - rxjs/observable/FromObservable.js - rxjs/operator/observeOn.js - rxjs/Notification.js - rxjs/observable/ArrayLikeObservable.js - rxjs/observable/IteratorObservable.js - rxjs/BehaviorSubject.js - app/header/header.component.js - app/footer/footer.component.js - app/app.component.js - @angular/platform-browser-dynamic - @angular/compiler
Build error
{ Error on fetch for app\+contact\contact.module.js at **file:///C:/Workspace/ng2-hello-world-lazy-routing-master/node_modules/app\+contact\contact.module.js**
        Error: ENOENT: no such file or directory, open 'C:\Workspace\ng2-hello-world-lazy-routing-master\node_modules\app\+contact\contact.module.js'
  originalErr:
   { Error: ENOENT: no such file or directory, open 'C:\Workspace\ng2-hello-world-lazy-routing-master\node_modules\app\+contact\contact.module.js'
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Workspace\\ng2-hello-world-lazy-routing-master\\node_modules\\app\\+contact\\contact.module.js' } }

**Comment by SamVerschueren** [comment]
I will update the repo tomorrow. I noticed at other repos that it fails due to updated dependencies.

**Comment by SamVerschueren** [comment]
@gonzalon I updated the dependencies but I don't think that is the real cause of this. I noticed that it looks for a path `app+contact\contact.module.js` while it should be `app\+contact\contact.module.js`. I assume you are using Windows for this? Maybe Windows fails on the `+`-sign in the path. I always use that to indicate that the module inside that directory is being lazy loaded. But if it doesn't work on Windows, I might have to change that in here.

Could your first try to check out the latest changes that I pushed right now. If that doesn't work, try these steps.

1. Rename the `app/+contact` directory to `app/contact`
2. In `make.js`, change the `path` in [this line](https://github.com/SamVerschueren/ng2-hello-world-lazy-routing/blob/master/make.js#L7) from `+contact` to `contact`.

Let me know what worked for you.

**Comment by gonzalon** [comment]
@SamVerschueren Thanks for your update. 
You were right, I'm on Windows and the + in the naming convention cause the error. 
But now I'm getting another error:


> bundling **app\contact\contact.module.js** - (dist/app/**/*.js - **dir**\contact/**/*.js) - app/main.js - app/app.module.js - app/app.routing.js - app/home/home.component.js - @angular/core - rxjs/Observable.js - rxjs/symbol/observable.js - rxjs/util/root.js - rxjs/util/toSubscriber.js - rxjs/Observer.js - rxjs/symbol/rxSubscriber.js - rxjs/Subscriber.js - rxjs/Subscription.js - rxjs/util/UnsubscriptionError.js - rxjs/util/errorObject.js - rxjs/util/tryCatch.js - rxjs/util/isFunction.js - rxjs/util/isObject.js - rxjs/util/isArray.js - rxjs/Subject.js - rxjs/SubjectSubscription.js - rxjs/util/ObjectUnsubscribedError.js - @angular/router - rxjs/operator/filter.js - @angular/platform-browser - @angular/common - rxjs/operator/mergeAll.js - rxjs/util/subscribeToResult.js - rxjs/InnerSubscriber.js - rxjs/symbol/iterator.js - rxjs/util/isPromise.js - rxjs/OuterSubscriber.js - rxjs/operator/last.js - rxjs/util/EmptyError.js - rxjs/observable/fromPromise.js - rxjs/observable/PromiseObservable.js - rxjs/operator/concatAll.js - rxjs/operator/catch.js - rxjs/operator/reduce.js - rxjs/operator/mergeMap.js - rxjs/operator/map.js - rxjs/operator/first.js - rxjs/operator/every.js - rxjs/operator/concatMap.js - rxjs/observable/of.js - rxjs/observable/ArrayObservable.js - rxjs/util/isScheduler.js - rxjs/observable/EmptyObservable.js - rxjs/observable/ScalarObservable.js - rxjs/observable/from.js - rxjs/observable/FromObservable.js - rxjs/operator/observeOn.js - rxjs/Notification.js - rxjs/observable/ArrayLikeObservable.js - rxjs/observable/IteratorObservable.js - rxjs/BehaviorSubject.js - app/header/header.component.js - app/footer/footer.component.js - app/app.component.js - @angular/platform-browser-dynamic - @angular/compiler
Build error
{ Error on fetch for app\contact\contact.module.js at file:///C:/Workspace/ng2-hello-world-lazy-routing-master/node_modules/app\contact\contact.module.js
        Error: ENOENT: no such file or directory, open 'C:\Workspace\ng2-hello-world-lazy-routing-master\node_modules\app\contact\contact.module.js'
  originalErr:
   { Error: ENOENT: no such file or directory, open 'C:\Workspace\ng2-hello-world-lazy-routing-master\node_modules\app\contact\contact.module.js'
     errno: -4058,
     code: 'ENOENT',
     syscall: 'open',
     path: 'C:\\Workspace\\ng2-hello-world-lazy-routing-master\\**node_modules**\\app\\contact\\contact.module.js' } }


Look at the path of the error, it's trying to get the file from the "node_modules" folder, I think the right path for the fetch should be:

C:\Workspace\ng2-hello-world-lazy-routing-master\dist\app\contact\contact.module.js  it's that right?

Another question, that it's not related: I'm seeing you are excluding in the expression the path 'dir' why is that?

**Comment by SamVerschueren** [comment]
Could you change [these 2 lines](https://github.com/SamVerschueren/ng2-hello-world-lazy-routing/blob/master/make.js#L13-L14) to

```js
'app\*': 'dist\app\*',
'aot\*': 'dist\aot\*',
```

And if that works, maybe to something like this

```js
[path.join('app', '*')]: path.join('dist', 'app', '*'),
[path.join('aot', '*')]: path.join('dist', 'aot', '*'),
```

This has probably something to do with the backward versus forward slashes.

**Comment by SamVerschueren** [comment]
That doesn't seem to solve it. I added AppVeyor that will try to build it for me but it keeps on failing https://ci.appveyor.com/project/SamVerschueren/ng2-hello-world-lazy-routing/history. Have to investigate a little further...

**Comment by SamVerschueren** [comment]
Did some changes and AppVeyor is building now so it should be working. Clone the repository again and try building.

**Comment by SamVerschueren** [comment]
Also fixed the [preload](https://github.com/SamVerschueren/ng2-hello-world-lazy-routing-preload) and [custom preload](https://github.com/SamVerschueren/ng2-hello-world-lazy-routing-custom-preload) builds.
